package_update: true
packages:
  - avahi-daemon

write_files:
  - content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock --host=fd:// --host=tcp://0.0.0.0:2375
    owner: root:root
    path: /etc/systemd/system/docker.service.d/httpapi.conf
    permissions: '0644'

runcmd:
  - curl --location --silent --output /etc/apt/keyrings/docker.asc https://download.docker.com/linux/ubuntu/gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release --codename --short) stable" | sudo tee /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get --no-install-recommends --yes install containerd.io docker-buildx-plugin docker-ce docker-ce-cli
  - apt-get clean
  - usermod --append --groups docker ubuntu
