package_update: true
packages:
  - avahi-daemon

write_files:
  - content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock --host=fd:// --host=tcp://0.0.0.0:2375
    owner: root:root
    path: /etc/systemd/system/docker.service.d/httpapi.conf
    permissions: '0644'

runcmd:
  - curl --location --silent https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release --codename --short) stable"
  - apt-get update
  - apt-get --no-install-recommends --yes install containerd.io docker-ce docker-ce-cli
  - usermod --append --groups docker ubuntu
